# Generated by Django 3.2.6 on 2022-01-10 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=200)),
                ('prix_categorie', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='parant',
            name='prenom_parent',
            field=models.CharField(max_length=100, verbose_name='prénom du parant'),
        ),
        migrations.AlterField(
            model_name='parant',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='numéro de téléphone'),
        ),
        migrations.CreateModel(
            name='Cours_particulier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(max_length=200)),
                ('prenom_etudiant', models.CharField(max_length=200)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='home.categorie', verbose_name='matiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='home.matiere', verbose_name='matiere')),
            ],
        ),
    ]
