# Generated by Django 3.2.6 on 2022-01-25 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_study_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='study_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fils', to='home.studylevel'),
        ),
    ]
