# Generated by Django 3.2.6 on 2022-01-25 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_student_study_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='study_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='home.studylevel'),
        ),
        migrations.AlterField(
            model_name='studylevel',
            name='classe',
            field=models.CharField(blank=True, choices=[('classe 1', 'Classe 1'), ('classe 2', 'Classe 2'), ('classe 3', 'Classe 3'), ('classe 4', 'Classe 4'), ('classe 5', 'Classe 5')], max_length=20, null=True, verbose_name='classe scolaire'),
        ),
        migrations.AlterField(
            model_name='studylevel',
            name='devision',
            field=models.CharField(blank=True, choices=[('Tronc_commun_science_et_technologie', 'Tronc commun science et technologie'), ('sciences expérimentales', 'sciences expérimentales'), ('Mathématiques', 'Mathématiques'), ('Athlète technique', 'Athlète technique')], max_length=50, null=True, verbose_name='Devision scolaire'),
        ),
    ]
