# Generated by Django 3.2.6 on 2022-01-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_villa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('validée et payée', 'Validée Et Payée'), ('pas encore', 'Pas Encore')], default='validée et payée', max_length=30),
        ),
    ]
