# Generated by Django 3.2.6 on 2022-01-21 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_facture_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, verbose_name="nom de l'activité")),
                ('activity_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100, verbose_name='nom du père')),
                ('father_firstname', models.CharField(max_length=100, verbose_name='prénom du père')),
                ('father_profession', models.CharField(max_length=300, verbose_name='profession du père')),
                ('father_phone', models.CharField(max_length=20, verbose_name='numéro de téléphone du père')),
                ('father_avatar', models.ImageField(upload_to='avatars/')),
                ('mother_name', models.CharField(max_length=100, verbose_name='nom et prénom de la mère')),
                ('mother_profession', models.CharField(max_length=300, verbose_name='profession de la mère')),
                ('mother_phone', models.CharField(max_length=20, verbose_name='numéro de téléphone de la mère')),
                ('authorized_people', models.TextField(verbose_name="personnes autorisées à recuperer l'eleve")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parant', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstname', models.CharField(max_length=200, verbose_name="nom de l'eleve")),
                ('student_name', models.CharField(max_length=200, verbose_name="prenom de l'eleve")),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name="date de naissance de l'eleve")),
                ('place_of_birth', models.CharField(max_length=200, verbose_name="Lieu de naissance de l'eleve")),
                ('address', models.CharField(max_length=300, verbose_name='Adresse')),
                ('allergic', models.TextField(default='', verbose_name='Allergie à signaler')),
                ('chronical_sickness', models.TextField(default='', verbose_name='maldie chronique à signaler')),
                ('particular_handicap', models.TextField(default='', verbose_name='handicape particulier à signaler')),
                ('student_gender', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10)),
                ('study_level', models.CharField(choices=[('prescolaire', 'Prescolaire'), ('preparatoire', 'Preparatoire'), ('primaire_1', 'Primaire_1'), ('primaire_2', 'Primaire_2'), ('primaire_3', 'Primaire_3'), ('primaire_4', 'Primaire_4'), ('primaire_5', 'Primaire_5'), ('primaire_6', 'Primaire_6'), ('moyenne_1', 'Moyenne_1'), ('moyenne_2', 'Moyenne_2'), ('moyenne_3', 'Moyenne_3'), ('moyenne_4', 'Moyenne_4'), ('lycéenne_1', 'Lycéenne_1'), ('lycéenne_2', 'Lycéenne_2'), ('lycéenne_3', 'Lycéenne_3'), ('lycéenne_4', 'Lycéenne_4')], default='prescolaire', max_length=200, verbose_name="niveau d'etude")),
                ('student_avatar', models.ImageField(upload_to='avatars/')),
                ('scolar_inscription_date', models.DateField(default=django.utils.timezone.now)),
                ('pedagogic_inscription_date', models.DateField(default=django.utils.timezone.now)),
                ('scolar_year', models.CharField(default='21/22', max_length=20, verbose_name='année scolaire')),
                ('last_school_attended', models.CharField(max_length=400, verbose_name='dernière école fréquentée')),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fils', to='home.activity')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fils', to='home.parent')),
            ],
        ),
        migrations.RemoveField(
            model_name='parant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Fils',
        ),
        migrations.DeleteModel(
            name='Parant',
        ),
    ]
