# Generated by Django 3.2.6 on 2022-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220125_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylevel',
            name='devision',
            field=models.CharField(blank=True, choices=[('tronc_commun_science_et_technologie', 'Tronc commun science et technologie'), ('laitre', 'Laitre'), ('science', 'Science'), ('mathélemes', 'Mathélemes'), ('technique math(mechanique)', 'Technique math(mechanique)'), ('technique math(electricité)', 'Technique math(electricité)'), ('technique math(génie civil)', 'Technique math(génie civil)'), ('gestion', 'Gestion'), ('philosophie', 'Philosophie'), ('langue espagnole', 'Langue Espagnole'), ('langue allemande', 'Langue Allemande')], max_length=50, null=True, verbose_name='Devision scolaire'),
        ),
    ]
