# Generated by Django 3.2.6 on 2022-01-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_studylevel_devision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='reste_a_paier',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='prix_matiere',
        ),
        migrations.AddField(
            model_name='cours_particulier',
            name='prix_matiere',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cours_particulier',
            name='study_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='particular_courses', to='home.studylevel'),
        ),
    ]
