# Generated by Django 3.2.6 on 2022-01-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220121_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='father_firstname',
        ),
    ]
