# Generated by Django 3.2.6 on 2022-02-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220129_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours_particulier',
            name='classe',
            field=models.CharField(choices=[('individuelle', 'Individuelle'), ('groupe', 'Groupe')], default='individuelle', max_length=20, verbose_name='le type de classe'),
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
    ]
