# Generated by Django 3.2.6 on 2022-01-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220121_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours_particulier',
            name='categorie',
        ),
        migrations.AddField(
            model_name='cours_particulier',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='home.categorie', verbose_name='classe'),
        ),
    ]
