# Generated by Django 3.2.6 on 2022-02-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cours_particulier_date_de_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours_particulier',
            name='classe',
        ),
        migrations.AddField(
            model_name='cours_particulier',
            name='cours_type',
            field=models.CharField(choices=[('individuelle', 'Individuelle'), ('groupe', 'Groupe')], default='individuelle', max_length=20, verbose_name='le type du cours'),
        ),
    ]
