# Generated by Django 3.2.6 on 2022-01-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220121_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Classe',
        ),
    ]
