# Generated by Django 3.2.6 on 2022-01-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_categorie_classe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='nom_categorie',
            new_name='nom_classe',
        ),
    ]
