# Generated by Django 3.2.6 on 2022-01-21 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_nom_categorie_classe_nom_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='magazin',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazin',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
