# Generated by Django 3.2.6 on 2022-01-22 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_facture_date_de_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='reste_a_paier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='chronical_sickness',
            field=models.TextField(blank=True, null=True, verbose_name='maladie chronique à signaler'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pedagogic_inscription_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="date d'inscription pedagogique"),
        ),
        migrations.AlterField(
            model_name='student',
            name='scolar_inscription_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="date d'inscription scolaire"),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_avatar',
            field=models.ImageField(upload_to='avatars/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10, verbose_name="le sexe de l'eleve"),
        ),
    ]
